pub mod fastembed;
#[cfg(target_os = "android")]
pub mod logcat;
pub mod memory;
pub mod native_host;
pub mod nearby_search;
pub mod registry;
pub mod reverse_geocode;
pub mod understand_scene;
pub mod weather;
